Update rETH pipeline

diff --git a/.github/workflows/ingest.yaml b/.github/workflows/ingest.yaml
--- a/.github/workflows/ingest.yaml
+++ b/.github/workflows/ingest.yaml
@@ -41,14 +41,18 @@ jobs:
             ipns_id: k51qzi5uqu5di44ukms656i7lfpx3kzy1eotzaa514pterzr6d73ee3ndmbs4t
             ipns_key_secret: CRYPTOCOMPARE_OHLCV_ETH_USD_KEY
             dnslink_subdomain: com.cryptocompare.ohlcv.eth-usd.ipns.kamu.dev
-          - dataset_name: net.rocketpool.reth.mint-burn
-            ipns_id: k51qzi5uqu5dj6e8rprw175y8tqt55ipji4c1maqqtpxl11gpnpd3qb7luta6r
-            ipns_key_secret: NET_ROCKETPOOL_RETH_MINT_BURN_KEY
-            dnslink_subdomain: net.rocketpool.reth.mint-burn.ipns.kamu.dev
           - dataset_name: co.alphavantage.tickers.daily.spy
             ipns_id: k51qzi5uqu5djln0j1uan84f9btedeqfi9inj1exw8xj4dp9tpc2znbedkcazy
             ipns_key_secret: CO_ALPHAVANTAGE_TICKERS_DAILY_SPY_KEY
             dnslink_subdomain: co.alphavantage.tickers.daily.spy.ipns.kamu.dev
+          - dataset_name: net.rocketpool.reth.tokens-minted
+            # ipns_id: k51qzi5uqu5dj6e8rprw175y8tqt55ipji4c1maqqtpxl11gpnpd3qb7luta6r
+            # ipns_key_secret: NET_ROCKETPOOL_RETH_MINT_BURN_KEY
+            # dnslink_subdomain: net.rocketpool.reth.tokens-minted.ipns.kamu.dev
+          - dataset_name: net.rocketpool.reth.tokens-burned
+            # ipns_id: k51qzi5uqu5dj6e8rprw175y8tqt55ipji4c1maqqtpxl11gpnpd3qb7luta6r
+            # ipns_key_secret: NET_ROCKETPOOL_RETH_MINT_BURN_KEY
+            # dnslink_subdomain: net.rocketpool.reth.tokens-burned.ipns.kamu.dev
     runs-on: ubuntu-latest
     steps:
       - uses: ibnesayeed/setup-ipfs@master
@@ -85,9 +89,9 @@ jobs:
             .kamu
           # TODO: Currently cache action will not update the cache upon hit and there is no option to do so
           # Below uses a workaround suggested here: https://github.com/actions/cache/issues/342#issuecomment-673371329
-          key: cachegen-9-kamu-dataset-${{ matrix.dataset_name }}-${{ github.run_id }}
+          key: kamu-dataset-${{ matrix.dataset_name }}-${{ github.run_id }}
           restore-keys: |
-            cachegen-9-kamu-dataset-${{ matrix.dataset_name }}-
+            kamu-dataset-${{ matrix.dataset_name }}-
 
       - uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -100,21 +104,21 @@ jobs:
       # This however puts us at risk of blowing past the rate limits on the public gateway.
       - name: Configure
         shell: bash
-        env:
-          IPNS_KEY: ${{ secrets[matrix.ipns_key_secret] }}
+        # env:
+        #   IPNS_KEY: ${{ secrets[matrix.ipns_key_secret] }}
         run: |
           # Add IPNS key
-          echo $IPNS_KEY | base64 -d > ipns_key
-          ipfs key import ${{ matrix.dataset_name }} ipns_key
-          rm ipns_key
+          # echo $IPNS_KEY | base64 -d > ipns_key
+          # ipfs key import ${{ matrix.dataset_name }} ipns_key
+          # rm ipns_key
 
           # Add pinning service
           # ipfs pin remote service add svc "$PINATA_API_URL" "$PINATA_ACCESS_TOKEN"
 
           # Create workspace and point kamu to IPFS gateway
-          kamu init || true
+          kamu init --exists-ok
           kamu list --output-format table -w
-          kamu config set protocol.ipfs.httpGateway "$IPFS_HTTP_GATEWAY"
+          # kamu config set protocol.ipfs.httpGateway "$IPFS_HTTP_GATEWAY"
 
       # TODO: We use DNSLink instead of IPNS due to IPNS's current usability issues like:
       # - frequent loss of writes
@@ -127,20 +131,20 @@ jobs:
       #     ipfs_cid=$(ipfs name resolve "/ipns/$IPNS_ID" | grep -oE "[^/]+$")
       #     echo "Current IPFS CID: $ipfs_cid"
 
-      - name: Resolve dataset
-        id: resolve-dataset
-        shell: bash
-        run: |
-          ipfs_cid=$( \
-            aws route53 list-resource-record-sets \
-            --hosted-zone-id $AWS_ROUTE53_HOSTED_ZONE_ID \
-            | jq -r ".ResourceRecordSets[] | select(.Name == \"_dnslink.${{ matrix.dnslink_subdomain }}.\") | .ResourceRecords[0].Value" \
-            | grep -oE '[^/]+"$' \
-            | grep -oE '^[^"]+'
-          )
-
-          echo "Current IPFS CID (from DNSLink): $ipfs_cid"
-          echo "CID=$ipfs_cid" >> $GITHUB_OUTPUT
+      # - name: Resolve dataset
+      #   id: resolve-dataset
+      #   shell: bash
+      #   run: |
+      #     ipfs_cid=$( \
+      #       aws route53 list-resource-record-sets \
+      #       --hosted-zone-id $AWS_ROUTE53_HOSTED_ZONE_ID \
+      #       | jq -r ".ResourceRecordSets[] | select(.Name == \"_dnslink.${{ matrix.dnslink_subdomain }}.\") | .ResourceRecords[0].Value" \
+      #       | grep -oE '[^/]+"$' \
+      #       | grep -oE '^[^"]+'
+      #     )
+      #
+      #     echo "Current IPFS CID (from DNSLink): $ipfs_cid"
+      #     echo "CID=$ipfs_cid" >> $GITHUB_OUTPUT
 
       # # TODO: This always times out!
       # - name: Pin dataset in local IPFS node
@@ -188,78 +192,78 @@ jobs:
       # TODO: We are not using `kamu push` here to avoid resolving and publishing into IPNS.
       # IPNS has proven to be unreliable and cause frequent timeouts, so we limit interactions to IPFS and then do
       # best-effort attempt to publish to IPNS.
-      - name: Publish dataset to IPFS
-        shell: bash
-        env:
-          OLD_CID: ${{ steps.resolve-dataset.outputs.CID }}
-          PIN_TRIES: "10"
-        run: |
-          # Add dataset to IPFS
-          ipfs_cid=$(kamu -v system ipfs add ${{ matrix.dataset_name }})
-          echo "New IPFS CID: $ipfs_cid"
-
-          if [ "$OLD_CID" == "$ipfs_cid" ]; then
-            echo "CID didn't change - skipping publishing"
-          else
-            # Pin new CID to replicate data to the pinning service
-            for i in $(seq 1 $PIN_TRIES); do
-              echo "Pinning CID (attempt $i)"
-
-              if curl --fail -sS -X POST -u "$INFURA_IPFS_PROJECT_ID:$INFURA_IPFS_PROJECT_SECRET" "https://ipfs.infura.io:5001/api/v0/pin/add?arg=$ipfs_cid"; then
-                echo "Successfully pinned"
-                break
-              else
-                echo "Pinning service returned an error: $response"
-
-                # TODO: Remove this debug stuff when pinning is reliable
-                peers_num=$(ipfs swarm peers | wc -l)
-                echo "IPFS is connected to $peers_num peers"
-
-                echo "IPFS addresses:"
-                ipfs id
-
-                if curl -s --fail "https://dweb.link/ipfs/$ipfs_cid" > /dev/null; then
-                  echo "CID is RESOLVABLE via public gateway"
-                else
-                  echo "CID is NOT resolvable via public gateway"
-                fi
-
-                if [ $i == $PIN_TRIES ]; then
-                  echo "Failed to pin CID after $PIN_TRIES attempts"
-
-                  # TODO: Pinning fails so often that we have to ignore this for now
-                  # not to obscure ingest errors.
-                  exit 0
-                fi
-              fi
-            done
-            # timeout 60 ipfs pin remote add --service svc --name ${{ matrix.dataset_name }} "/ipfs/$ipfs_cid"
-
-            # Update DNSLink entry
-            echo "{
-                \"Comment\": \"GHAction update of DNSLink record\",
-                \"Changes\": [
-                    {
-                        \"Action\": \"UPSERT\",
-                        \"ResourceRecordSet\": {
-                            \"Name\": \"_dnslink.${{ matrix.dnslink_subdomain }}.\",
-                            \"Type\": \"TXT\",
-                            \"TTL\": $AWS_ROUTE53_TTL,
-                            \"ResourceRecords\": [{
-                                \"Value\": \"\\\"dnslink=/ipfs/$ipfs_cid\\\"\"
-                            }]
-                        }
-                    }
-                ]
-            }" > dns-upsert.json
-            echo "Updating DNSLink entry with: $(cat dns-upsert.json)"
-            aws route53 change-resource-record-sets --hosted-zone-id $AWS_ROUTE53_HOSTED_ZONE_ID --change-batch file://dns-upsert.json
-
-            # TODO: IPNS is not ready for use
-            # # Try publishing to IPNS (best effort)
-            # echo "Attempting to publish to IPNS"
-            # timeout 60 ipfs name publish --resolve=false --key=${{ matrix.dataset_name }} /ipfs/$ipfs_cid || true
-          fi
+      # - name: Publish dataset to IPFS
+      #   shell: bash
+      #   env:
+      #     OLD_CID: ${{ steps.resolve-dataset.outputs.CID }}
+      #     PIN_TRIES: "10"
+      #   run: |
+      #     # Add dataset to IPFS
+      #     ipfs_cid=$(kamu -v system ipfs add ${{ matrix.dataset_name }})
+      #     echo "New IPFS CID: $ipfs_cid"
+      #
+      #     if [ "$OLD_CID" == "$ipfs_cid" ]; then
+      #       echo "CID didn't change - skipping publishing"
+      #     else
+      #       # Pin new CID to replicate data to the pinning service
+      #       for i in $(seq 1 $PIN_TRIES); do
+      #         echo "Pinning CID (attempt $i)"
+      #
+      #         if curl --fail -sS -X POST -u "$INFURA_IPFS_PROJECT_ID:$INFURA_IPFS_PROJECT_SECRET" "https://ipfs.infura.io:5001/api/v0/pin/add?arg=$ipfs_cid"; then
+      #           echo "Successfully pinned"
+      #           break
+      #         else
+      #           echo "Pinning service returned an error: $response"
+      #
+      #           # TODO: Remove this debug stuff when pinning is reliable
+      #           peers_num=$(ipfs swarm peers | wc -l)
+      #           echo "IPFS is connected to $peers_num peers"
+      #
+      #           echo "IPFS addresses:"
+      #           ipfs id
+      #
+      #           if curl -s --fail "https://dweb.link/ipfs/$ipfs_cid" > /dev/null; then
+      #             echo "CID is RESOLVABLE via public gateway"
+      #           else
+      #             echo "CID is NOT resolvable via public gateway"
+      #           fi
+      #
+      #           if [ $i == $PIN_TRIES ]; then
+      #             echo "Failed to pin CID after $PIN_TRIES attempts"
+      #
+      #             # TODO: Pinning fails so often that we have to ignore this for now
+      #             # not to obscure ingest errors.
+      #             exit 0
+      #           fi
+      #         fi
+      #       done
+      #       # timeout 60 ipfs pin remote add --service svc --name ${{ matrix.dataset_name }} "/ipfs/$ipfs_cid"
+      #
+      #       # Update DNSLink entry
+      #       echo "{
+      #           \"Comment\": \"GHAction update of DNSLink record\",
+      #           \"Changes\": [
+      #               {
+      #                   \"Action\": \"UPSERT\",
+      #                   \"ResourceRecordSet\": {
+      #                       \"Name\": \"_dnslink.${{ matrix.dnslink_subdomain }}.\",
+      #                       \"Type\": \"TXT\",
+      #                       \"TTL\": $AWS_ROUTE53_TTL,
+      #                       \"ResourceRecords\": [{
+      #                           \"Value\": \"\\\"dnslink=/ipfs/$ipfs_cid\\\"\"
+      #                       }]
+      #                   }
+      #               }
+      #           ]
+      #       }" > dns-upsert.json
+      #       echo "Updating DNSLink entry with: $(cat dns-upsert.json)"
+      #       aws route53 change-resource-record-sets --hosted-zone-id $AWS_ROUTE53_HOSTED_ZONE_ID --change-batch file://dns-upsert.json
+      #
+      #       # TODO: IPNS is not ready for use
+      #       # # Try publishing to IPNS (best effort)
+      #       # echo "Attempting to publish to IPNS"
+      #       # timeout 60 ipfs name publish --resolve=false --key=${{ matrix.dataset_name }} /ipfs/$ipfs_cid || true
+      #     fi
 
       # - name: Ingest & push loop
       #   shell: bash
